version: '3.9'

services:
  client1:
    container_name: client1
    build: 
      context: ./client
    networks:
      - inquisitor

  client2:
    container_name: client2
    build:
      context: ./client
    networks:
      - inquisitor

  router:
    container_name: router
    build:
      context: ./router
    networks:
      - inquisitor
  
networks:
  inquisitor:
    driver: bridge