FROM python:3
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir cryptography pyAesCrypt

RUN mkdir /app
RUN mkdir /root/infection
COPY ./infection /root/infection

COPY main.py /app/main.py
COPY supported_extensions /app/supported_extensions

CMD ["tail", "-f"]